* 分解数据
  数据分析就是仔细推敲证据。目的是做出更好的决策。

  了解问题->分解问题和数据->评估->决策

** 确定目标
  确定问题很重要，不能推卸自己解决问题和建议决策的义务。
  尽量从客户那里多了解一些信息，才能确定问题。

  仅仅过一眼并不是数据分析，数据分析总的来说就是认清问题，继而解决问题。

  有些人把问题视为机会，指出如何发现机会则能赢得竞争优势。

  确定量化目标，弄清数据的意义。

** 把问题和数据分解为更小的块
   将问题划分为可管理、可解决的组块。

   找出高效的比较因子。进行有效的比较是数据分析的核心。

** 评估
   评估分解组块的关键就是比较，通过对这些因子进行比较，你看出了什么？

   分析从你介入的那一刻开始，数据分析就是你的一切：你的信念，你的判断，你的信用。
   只要你在分析中明白地展现自己，成功就更有希望。

   在撰写最终报告的时候，一定要提到你自己，这样客户才知道你的结论出自何处。

** 提出建议
   你的工作就是让自己和客户仔细研究你对数据的评估，洞察先机，从而有能力作出更好的决策。

   你的最终报告要能简单则简单，但不可简单过头！你的工作是确保自己的意见传达到位，让人们根据你的意见做出正确的决策。 提交给客户的报告要以得到客户理解、鼓励客户以数据为基础做出明智的决策为重点。

** 心智模型
   你对外界的假设和你确信的观点就是你的心智模型。

   现实世界非常复杂，心智模型大大影响你对数据的解释。

   统计模型取决于心智模型。心智模型决定你的观察结果，是你观察现实的棱镜。
   你无法看到一切，因此你的大脑必须做出选择，以便集中注意力，这就是所谓的心智模型大大决定观察结果。

   心智模型应当包括你不了解的因素，一定要指出不确定因素。了解自己的知识缺陷非常重要。

   你无法无所不知，世界总是在不断变化，这就是严谨地指定问题并管理心智模型不确定因素成为工作重点的原因。

   搜集数据很重要，什么时候停止？

   错误的假设注定分析会得出错误的答案。一旦得到的数据与你的假设不符，就要立即回头重新详加思考。

   回顾问题、提炼模型、基于新模型观察世界，都是分析师工作的基本组成部分。

* 检验你的理论
  通过实验进行实证检验。

  统计与分析最基本的原理之一就是比较法。
