#+TITLE: 数据分析学习笔记
#+DESCRIPTION: 学习数据分析的学习笔记,Head first系列
#+KEYWORDS: 数据分析
#+CATEGORIES: 数据分析
#+LANGUAGE: zh-CN
#+latex_compiler: lualatex
#+LATEX_HEADER: \usepackage{ctex}

* 分解数据
  数据分析就是仔细推敲证据。目的是做出更好的决策。

  了解问题->分解问题和数据->评估->决策

** 确定目标
  确定问题很重要，不能推卸自己解决问题和建议决策的义务。
  尽量从客户那里多了解一些信息，才能确定问题。

  仅仅过一眼并不是数据分析，数据分析总的来说就是认清问题，继而解决问题。

  有些人把问题视为机会，指出如何发现机会则能赢得竞争优势。

  确定量化目标，弄清数据的意义。

** 把问题和数据分解为更小的块
   将问题划分为可管理、可解决的组块。

   找出高效的比较因子。进行有效的比较是数据分析的核心。

** 评估
   评估分解组块的关键就是比较，通过对这些因子进行比较，你看出了什么？

   分析从你介入的那一刻开始，数据分析就是你的一切：你的信念，你的判断，你的信用。
   只要你在分析中明白地展现自己，成功就更有希望。

   在撰写最终报告的时候，一定要提到你自己，这样客户才知道你的结论出自何处。

** 提出建议
   你的工作就是让自己和客户仔细研究你对数据的评估，洞察先机，从而有能力作出更好的决策。

   你的最终报告要能简单则简单，但不可简单过头！你的工作是确保自己的意见传达到位，让人们根据你的意见做出正确的决策。 提交给客户的报告要以得到客户理解、鼓励客户以数据为基础做出明智的决策为重点。

** 心智模型
   你对外界的假设和你确信的观点就是你的心智模型。

   现实世界非常复杂，心智模型大大影响你对数据的解释。

   统计模型取决于心智模型。心智模型决定你的观察结果，是你观察现实的棱镜。
   你无法看到一切，因此你的大脑必须做出选择，以便集中注意力，这就是所谓的心智模型大大决定观察结果。

   心智模型应当包括你不了解的因素，一定要指出不确定因素。了解自己的知识缺陷非常重要。

   你无法无所不知，世界总是在不断变化，这就是严谨地指定问题并管理心智模型不确定因素成为工作重点的原因。

   搜集数据很重要，什么时候停止？

   错误的假设注定分析会得出错误的答案。一旦得到的数据与你的假设不符，就要立即回头重新详加思考。

   回顾问题、提炼模型、基于新模型观察世界，都是分析师工作的基本组成部分。

* 检验你的理论
  通过实验进行实证检验。一个好的实验即能解决问题，又能揭示事物的真正运行规律。一个好实验往往能让你摆脱对观察数据的无限依赖，帮你理清因果关系;可靠的实证数据将让你的分析判断更有说服力。

  统计与分析最基本的原理之一就是比较法。数据只有通过相互比较才会有意义。(特别是随着时间变化的数据)

  比较越多，分析结果越正确。(数据，数据，实验，实验)

  使用观察研究的方法时，应当假定其他因素会混杂你的结论，因为你无法像控制实验那样控制这些因素。当你开始怀疑因果关系的走向时，请进行反方向思考。

  涉及判定因果关系时，观察研究法并不是那么强大有力.

  观察分析法充满混杂因素，它们不是你试图进行比较的因素，最终会导致分析结果的敏感度变差。
  要不断考虑混杂因素对分析结果的影响。想象哪些变量可能会影响你的分析结果。无论你的量化技术多么出神入化，真正的重点却永远在于：分析结论要 *有意义* 。

  拆分数据块，管理混杂因素。

  要对策略进行实验，以得到数据支持。好的实验要有控制组(对照组)，才能用比较法观察。没有控制组就意味着没有比较，没有比较就意味着无法对所发生的情况进行判断。 应当对历史控制法表示怀疑。

  混杂因素是所研究的各个组之间的差异。为了 *有效地进行比较* ，各个组必须相同。

  随机选择相似组

* 最优化
  人人都想多多益善，为此我们要调整决策变量，找出解决方案和优化点，使我们最大限度地达到目标。

  将所需要的数据分成两类：无法控制的因素，可以控制的因素。

  你能控制的变量受到约束条件的限制。决策变量是你能控制的因素，约束条件告诉你无法做到的事。

  你的目标应该是尽量创建最有用的模型，让模型的不完美相对分析目标变得无足轻重。

** 按照分析目标校正假设
   你的假设应该详尽到什么程度？由分析的重要性来决定。

   创建模型时，务必要规定假设中各种变量的相互关系。例如，假设下个月的销量仍然保持前几个月的销售趋势。

   你的假设立足于不断变化的实际情况。做好修改模型的准备。

* 数据图形化

  每当观察一张新图片，一上来就该问“图片中隐含了哪些数据？”你所关心的是数据的质量及其含义，炫目的设计会妨碍你做出分析判断。  数据图形要体现数据，优秀的数据分析自始至终都离不开“用数据思考”。

  数据庞杂过多，记住你的分析目标，目光停留在和目标有关的数据上，无视其它。

  让数据变美观也不是你要解决的问题。

  数据图形化的根本在于正确比较。首先要明确能够实现客户目标的基本比较对象。

  优秀图形展示数据，作出高明的比较，展示多个变量。

  散点图是探索性数据分析的奇妙工具,使用散点图发现因果关系(相关？)。
  通常用X轴代表自变量(假想为原因的变量)，Y轴代表应变量(假想为结果的变量)。不必去论证因果，因为我们是在探索数据，原因正是我们的探索目标。

  有效的比较是数据分析的基础，尽量让图形多元化最有可能促成最有效的比较。
  
  模型与数据吻合，看起来最合情理。
   
* 假设并非如此 
  通过数据分析仔细推理，细致地评估大量备选答案，然后将手头的一切信息整合到各种模型中。证伪法就是一种切实有效的非直觉方法。

  变量之间可以正相关，也可以负相关。将变量关系编织成一个模型。
  
  现实世界中的各种原因呈网络关系，而非线性关系。 线性等于直觉。在一个活跃、多变、互有联系的系统中制定决策。要渴望看出因果关系网络。

  用手头的资料进行假设检验。

** 假设检验的核心是证伪
   剔除无法证实的假设，就是证伪。选出看上去最可信的第一个假设的做法称为满意法。证伪法更可靠。
   满意法容易形成偏见，坚持选择的假设。证伪法让人们对各种假设感觉更敏锐，防止掉入认知陷阱。

   可以克服人们专注于错误答案而无视于其他答案的天然倾向。

   简单罗列所有假设，对结论不承担任何责任，只做了数据传递工作，不是数据分析师的工作。

** 借助诊断性找出否定性最小的假设
   只要能够帮助你评估各种假设的相对强度，证据和数据就具有诊断性。

   进行假设检验时，重点是要识别和找出诊断证据，非诊断证据不会给你带来任何进展。

   无法一一剔除所有假设，但可以判定哪个假设最强。

* 贝叶斯统计
  数据收集工作永不停息。碰到直接概率问题就需要贝叶斯规则，利用基础概率和波动数据做到明察秋毫。

  假阳性:误检， 真阴性:漏检。 

** 条件概率
   以一件事的发生为前提的另一件事的发生概率。

   基础概率，又称作事前概率。忽略事前数据因此做出错误决策，就是基础概率谬误。

   新信息会改变你的基础概率

* 信念数字化
  主观概率就是将严谨融入直觉的简便办法。主观概率体现专家信念。

  主观概率是对分歧内容和分歧大小的一种精确规范，分析师用主观概率帮助自己抓住问题焦点，以图解决问题。

  每个人都能理解主观概率，但它远没有得到充分的运用。

  优秀的数据分析师同时也是优秀的沟通者，主观概率则是一种向别人精确地传达你的想法和信念的富有启示性的表达方法。

  标准偏差量度的是典型的分析点与数据集平局值的差距。数据集中的大部分点都会落在平均值的一个标准偏差范围内。

  贝叶斯规则是修正主观概率的好办法。

* 启发法
  对工作计量
