#+TITLE: 线性代数学习笔记二
#+DESCRIPTION: 学习线性代数及其应用读书笔记
#+KEYWORDS: 数学, linear algebra
#+CATEGORIES: 数学
#+LANGUAGE: zh-CN
#+latex_compiler: lualatex
#+LATEX_HEADER: \usepackage{ctex}
#+OPTIONS: author:nil

* 线性方程组
  矩阵记号是为解方程组带来方便。 解方程组，消元法。

  三种基本变换对应于增广矩阵的下列变换:

  *行初等变换*
  1. (倍加变换 replacement) 把某一行换成它本身与另一行的倍数的和
  2. (对换变换 interchange) 把两行对换
  3. (倍乘变换 scaling) 把某一行的所有元素乘以同一个非零数

  行变换可应用于任何矩阵.如果一个矩阵可以经过一系列行初等变换变成另一个矩阵，则称这两个矩阵是行等价的。

  行变换是可逆的。

  线性方程组的两个基本问题：
  1. 方程组是否相容，即它是否至少有一个解？
  2. 若它有解，是否只有一个解，即解是否唯一？

** 行化简与阶梯型矩阵
   非零行或列指矩阵中至少包含一个非零元素的行或列，非零行的先导元素是指该行中最左边的非零元素。

   一个矩阵称为阶梯型，则有以下三个性值:
   1 每一非零行在每一零行之上
   2 某一行的先导元素所在的列位于前一行先导元素的右面
   3 某一先导元素所在列下方元素都是零。若一个阶梯型矩阵还满足以下性质，则称它为简化阶梯形：
   4 每一非零行的先导元素是1
   5 每一先导元素1是该元素所在列的唯一非零元素

   一个矩阵可以行化简变为阶梯形矩阵，但不同的方法可以化为不同的阶梯形矩阵。一个矩阵只能化为唯一的简化阶梯形矩阵。

   每个矩阵行等价于唯一的简化阶梯形矩阵。大部分矩阵程序用RREF作为简化阶梯形的缩写，有些用REF作为阶梯形的缩写。

*** 主元位置
    矩阵经过行变换化为阶梯形后，经进一步的行变换将矩阵化为简化阶梯形时，先导元素的位置并不改变。

    矩阵中的主元位置是A中对应于它的阶梯形中先导元素的位置。主元列是A的含有主元位置的列。

    用不同的行变换产生不同的主元。

    行简化算法，向前步骤，向后步骤。

*** 线性方程组的解
    行简化算法应用于方程组的增广矩阵时，可以得出线性方程组解集的一种显式示法。

    对应主元列的变量称为基本变量，其它变量称为自由变量。自由变量是指它可取任意值。

    解集的参数表示

    有自由变量的方程有无穷多个解

    线性方程组相容的充要条件是增广矩阵的最右列不是主元列。就是说，增广矩阵的阶梯形没有
    [0 ... 0 b] b \neq 0的行，如果线性方程组相容，它的解集可能有两种情形:
    - 当没有自由变量时，有唯一解。
    - 若至少有一个自由变量，有无穷多解。

#+INCLUDE: ~/code/clojure/kehan_algebra.clj src clojure

** 向量方程
   仅含一列的矩阵称为列向量，或简称向量。

   所有两个元素的向量的集记为R^2, R表示向量中的元素是实数，指数2表示每个向量包含2个元素。

   给定R^n 中向量v_1, v_2,  ..., v_p 和标量 c_1, c_2, ..., c_p ,向量
   \[
   y = c_1v_1+...+c_pv_p
   \]
   称为向量v_1, v_2, ..., v_p 以c_1, c_2, ..., c_p 为权的线性组合。

   向量方程
   \[ x_1a_1+x_2a_2+...+x_na_n=b\]
   和增广矩阵为
   \begin{equation} \label{eq:m1} [a_1 \quad a_2 \quad ... \quad a_n \quad b] \end{equation}
   的线性方程组有相同的解集。特别地， *b*  可以表示为 *a_1, a_2, ..., a_n* 的线性组合，当且仅当对应于 \eqref{eq:m1} 式的方程组有解.

** 矩阵方程
   若A是mxn矩阵，它的各列为a_1, ..., a_n. 若x是R^n 中向量,则A与x的积,记为Ax,就是A的各列以x中对应元素为权的线性组合，即
   \[
   Ax=\begin{bmatrix}
   a_1 & a_2 & \dots & a_n
   \end{bmatrix} \begin{bmatrix}
   x_1 \\
   x_2 \\
 \vdots \\
  x_n
\end{bmatrix} = x_1a_1 + x_2a_2 + \dots + x_n a_n
   \]

   称Ax=b这样的方程为矩阵方程

   至此，线性方程组有三种不同但彼此等价的观点:作为矩阵方程、作为向量方程或作为线性方程组。
   都用行化简算法来化简增广矩阵来解。

   主对角线上元素为1，其他位置元素为0，这个矩阵称为单位矩阵。记为I

** 线性方程组的解集
   如果线性方程组可以写成Ax=0的形式，则称为齐次的，A是mxn矩阵，0是R^n 中的零向量。这样的方程组至少有一个解，即x=0,这个解称为它的平凡解。

   齐次方程Ax=0有非平凡解，当且仅当方程至少有一个自由变量。

