#+TITLE: Learning How to Learn学习笔记--第1部分
#+DESCRIPTION: 本节学习内容: 如何学习
#+KEYWORDS: Learn
#+CATEGORIES: 学习
#+LANGUAGE: zh-CN

* 如何学习
  思考模式：
  - 专注模式(focused),一心一意全神贯注于想要学习或理解的事物。
  - 发散模式(diffuse modes)，联想。

  思维模式,为了得到不同的思维模式，就需要发散思考。
  发散模式不能专注于问题。
  
  类比

  当学习一些新的困难的东西时，大脑需要在两种学习模式之间来回切换，帮助你更高效地学习。
  每天锻炼，逐步增长。 *每天做一点* 这就是关键所在。

* 什么是学习
  大脑是如何运作的。我们有意识的仅仅是一小部分。大脑认知是动态的。突触不断产生与消亡。
  学习会修改大脑结构。睡眠。
  
  记忆存储在亿万个神经突触里。

* 拖延症
  当碰到一件非常不愿意做的事，就激活了大脑中与疼痛相关的区域。大脑就会自然而然地去寻找停止这种负面刺激的方式。
  这一方式就是将你的注意力转移到其他事情上。  番茄工作法，25分钟一个阶段，然后奖励自己。
  等同于大脑锻炼后放松。
  
  一步步掌握窍门。 越是抽象的东西，越要注重练习。
  你学习的东西是抽象的，但你创造的神经思维模式是真实且具体的。 通过练习，形成稳固的神经元模式。
  一心一意地专注，拼命学习它。然后休息下， 稍稍转移注意力。在放松的时间里，大脑的发散模式有机会在后台工作，帮你完成对概念的理解。你的神经通路就有个得到固化的机会。 番茄时钟工作法就是帮你形成稳固的有条理的神经思维模式。

* 记忆概论
  - 长期记忆，就像一个储存仓库，分布在一个大的区域中。
  - 工作记忆,大脑即时且有意识地处理信息时所涉及的那部分记忆，以前认为能存储7个组块，现在共识是只能存储大约4个组块的信息。我们会自动将记忆项和并为组块的形式。
  
  当遇到新事物时，你通常会运用工作记忆来处理它。如果想存入长期记忆，则需要一些时间和练习的过程。有种技巧可以促进这一过程，叫做间隔重复。不断重复你要记忆的东西，但重复的过程必须间隔开。需要时间才有持久的记忆结构。 不要想一次重复很多次，效果比间隔几天重复相同的次数差很多，会造成结构不稳定。

* 睡眠的重要性
  绝对清醒会让大脑产生有毒物质。睡眠可以排出毒素。代谢毒素会让你思维混乱。

  睡眠时，大脑会将你学习和思考过的想法和概念进行整理。在睡眠或打盹前复习下当天所学的内容，记忆效果会更好。
* 访谈
  单刀直入的实践， 大量的阅读作用甚微。 Learning by doing. 积极参与会让你学到更多。

  跑步，锻炼放松进行发散思维。 抵御想要同时进行多项任务的冲动。

  如果缺乏足够的空间，锻炼也能增强神经元。交流，讨论。

  对于成功，重要的不是聪明，是激情与努力。

  用不同的视角发现身边的事物。


  不花时间，坚实的知识结构就不会形成，大脑需要时间才能形成稳定的神经结构，因此不要一天重复很多次，要有间隔多次重复。
